import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Copy, 
  Download, 
  Share2, 
  RefreshCw, 
  MessageSquare, 
  FileText,
  Code2,
  TestTube,
  Shield,
  Zap,
  GitCompare,
  ExternalLink,
  BookOpen,
  MoreHorizontal
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { copyToClipboard, downloadTextFile } from '@/lib/downloadFile';

const EnhancedQuickActions = ({ 
  result, 
  resultId, 
  onRetry, 
  onAskFollowup, 
  onCompareWithPrevious,
  onOpenCollaboration,
  onExplainDeeper 
}) => {
  const [showMore, setShowMore] = useState(false);

  if (!result) return null;

  const handleCopyFixedCode = async () => {
    if (!result.correctedCode) {
      toast.error('No fixed code available');
      return;
    }
    await copyToClipboard(result.correctedCode);
    toast.success('Fixed code copied to clipboard!');
  };

  const handleCopyOriginalCode = async () => {
    if (!result.input) {
      toast.error('No original code available');
      return;
    }
    await copyToClipboard(result.input);
    toast.success('Original code copied to clipboard!');
  };

  const handleExportPDF = () => {
    // Create comprehensive report
    const report = `
# DevInspectAI Code Review Report

**Generated:** ${new Date().toLocaleString()}
**Language:** ${result.language?.toUpperCase() || 'Unknown'}
**Mode:** ${result.mode?.toUpperCase() || 'Unknown'}
**AI Score:** ${result.aiScore}/100

## Executive Summary
${result.explanation || 'No explanation provided.'}

## Issues Found (${result.errors?.length || 0})
${(result.errors || []).map((error, idx) => `
### ${idx + 1}. ${error.severity?.toUpperCase() || 'UNKNOWN'} - ${error.category || 'General'}
**Line:** ${error.line || 'N/A'}
**Message:** ${error.message || 'No message'}
${error.why ? `**Why:** ${error.why}` : ''}
${error.fix ? `**Fix:** ${error.fix}` : ''}
`).join('\n')}

## Suggestions (${result.suggestions?.length || 0})
${(result.suggestions || []).map((suggestion, idx) => `${idx + 1}. ${suggestion}`).join('\n')}

## Original Code
\`\`\`${result.language || 'text'}
${result.input || 'No code provided'}
\`\`\`

## Refactored Code
\`\`\`${result.language || 'text'}
${result.correctedCode || 'No refactored code provided'}
\`\`\`

---
*Generated by DevInspectAI - AI-Powered Code Review Platform*
    `.trim();

    downloadTextFile(report, `code-review-${Date.now()}.md`);
    toast.success('Report exported as Markdown!');
  };

  const handleShareAnalysis = async () => {
    if (!resultId) {
      toast.error('Cannot share - no analysis ID');
      return;
    }

    const shareUrl = `${window.location.origin}/shared/${resultId}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'DevInspectAI Code Review',
          text: `Check out this code review analysis (Score: ${result.aiScore}/100)`,
          url: shareUrl
        });
        toast.success('Analysis shared!');
      } catch (err) {
        if (err.name !== 'AbortError') {
          await copyToClipboard(shareUrl);
          toast.success('Share link copied to clipboard!');
        }
      }
    } else {
      await copyToClipboard(shareUrl);
      toast.success('Share link copied to clipboard!');
    }
  };

  const handleGenerateTests = () => {
    if (!result.input) {
      toast.error('No code available for test generation');
      return;
    }
    
    // This would trigger the AI assistant to generate tests
    onAskFollowup?.('Generate comprehensive unit tests for this code');
    toast.info('Generating unit tests...');
  };

  const handleSecurityScan = () => {
    if (!result.input) {
      toast.error('No code available for security scan');
      return;
    }
    
    onAskFollowup?.('Perform a detailed security vulnerability scan on this code');
    toast.info('Running security scan...');
  };

  const handlePerformanceAnalysis = () => {
    if (!result.input) {
      toast.error('No code available for performance analysis');
      return;
    }
    
    onAskFollowup?.('Analyze the performance characteristics and suggest optimizations for this code');
    toast.info('Analyzing performance...');
  };

  const primaryActions = [
    {
      icon: Copy,
      label: 'Copy Fix',
      onClick: handleCopyFixedCode,
      show: !!result.correctedCode,
      variant: 'default'
    },
    {
      icon: Download,
      label: 'Export',
      onClick: handleExportPDF,
      show: true,
      variant: 'outline'
    },
    {
      icon: Share2,
      label: 'Share',
      onClick: handleShareAnalysis,
      show: !!resultId,
      variant: 'outline'
    },
    {
      icon: RefreshCw,
      label: 'Retry',
      onClick: onRetry,
      show: !!onRetry,
      variant: 'outline'
    }
  ].filter(action => action.show);

  const secondaryActions = [
    {
      icon: Code2,
      label: 'Copy Original',
      onClick: handleCopyOriginalCode,
      show: !!result.input
    },
    {
      icon: TestTube,
      label: 'Generate Tests',
      onClick: handleGenerateTests,
      show: !!result.input
    },
    {
      icon: Shield,
      label: 'Security Scan',
      onClick: handleSecurityScan,
      show: !!result.input
    },
    {
      icon: Zap,
      label: 'Performance',
      onClick: handlePerformanceAnalysis,
      show: !!result.input
    },
    {
      icon: GitCompare,
      label: 'Compare',
      onClick: onCompareWithPrevious,
      show: !!onCompareWithPrevious
    },
    {
      icon: ExternalLink,
      label: 'Collaborate',
      onClick: onOpenCollaboration,
      show: !!onOpenCollaboration
    },
    {
      icon: BookOpen,
      label: 'Explain Deeper',
      onClick: onExplainDeeper,
      show: !!onExplainDeeper
    },
    {
      icon: MessageSquare,
      label: 'Ask AI',
      onClick: onAskFollowup,
      show: !!onAskFollowup
    }
  ].filter(action => action.show);

  return (
    <div className="space-y-2">
      {/* Primary Actions - Always Visible */}
      <div className="flex items-center gap-2 flex-wrap">
        {primaryActions.map(({ icon: Icon, label, onClick, variant }) => (
          <motion.div
            key={label}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            <Button
              onClick={onClick}
              size="sm"
              variant={variant}
              className="h-8 text-xs font-bold gap-1.5 shadow-sm"
            >
              <Icon className="w-3.5 h-3.5" />
              {label}
            </Button>
          </motion.div>
        ))}
        
        {secondaryActions.length > 0 && (
          <Button
            onClick={() => setShowMore(!showMore)}
            size="sm"
            variant="ghost"
            className="h-8 w-8 p-0"
          >
            <MoreHorizontal className="w-4 h-4" />
          </Button>
        )}
      </div>

      {/* Secondary Actions - Expandable */}
      <AnimatePresence>
        {showMore && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="flex items-center gap-1.5 flex-wrap pt-2 border-t border-border/20">
              {secondaryActions.map(({ icon: Icon, label, onClick }) => (
                <motion.div
                  key={label}
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <button
                    onClick={onClick}
                    className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-[10px] font-bold bg-muted/50 hover:bg-muted border border-border/20 text-muted-foreground hover:text-foreground transition-all"
                  >
                    <Icon className="w-3 h-3" />
                    {label}
                  </button>
                </motion.div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Quick Stats */}
      <div className="flex items-center gap-4 text-xs text-muted-foreground pt-1">
        <span>Issues: {result.errors?.length || 0}</span>
        <span>Score: {result.aiScore}/100</span>
        <span>Language: {result.language?.toUpperCase() || 'Unknown'}</span>
        {result.timestamp && (
          <span>
            {new Date(result.timestamp).toLocaleTimeString()}
          </span>
        )}
      </div>
    </div>
  );
};

export default EnhancedQuickActions;